"""add brand to products

Revision ID: 6c1554cf865b
Revises: 09a1c3bf0c17
Create Date: 2026-08-12 16:52:29.007357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c1554cf865b'
down_revision: Union[str, Sequence[str], None] = '09a1c3bf0c17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('brand', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'brand')
    # ### end Alembic commands ###
